### ISSUE TITLE
Removal of Theme Name in Template Parts for Improved Portability

### ISSUE THREAD

**Issue by alexdeborba** [atmostfear-entertainment/aegis#16]
**Description:**

The inclusion of the `themename` in `template parts` can potentially limit the portability and flexibility of the theme. Specifically, if the theme folder's name changes, it can lead to broken links or missing `template parts`. By omitting the `themename` from `template parts`, we can ensure that these parts will display correctly regardless of the theme's installation folder name. This issue is related to [Issue #4](https://github.com/atmostfear-entertainment/aegis/issues/4).

**Step-by-step Reproduction Instructions:**

1. Rename the Aegis theme folder to a different name.
2. Activate the theme and navigate to a page or post.
3. Observe any missing or improperly loaded `template parts` that have the theme name hardcoded in their paths.

**Expected Behavior:**

`Template parts` should load seamlessly irrespective of the theme folder's name. Removing the `themename` from `template parts`' paths will ensure consistent display and functionality across various installation scenarios.

**Suggested Solution:**

Refactor the `template parts` to remove any hardcoded references to the `themename`. Instead, leverage dynamic methods to fetch `template parts`, ensuring the theme remains robust and adaptable to changes in its installation directory.

**Comment by atmostfear-entertainment** [comment]
**Enhancement:** Use consistent pattern titles, slugs and file names.

- 404.html
- archive.html
- archive-product.html
- index.html
- page.html
- search.html
- single.html
- single-product.html
- taxonomy-product_cat.html
- taxonomy-product_tag.html
