### ISSUE TITLE
Local font installation from google font (outdated format)

### ISSUE THREAD

**Issue by eliquame** [atmostfear-entertainment/aegis#29]
I'm testing Alpha 3 version with latest WP and WC version.

It's not quite a BUG Report, it's somewhere between a Bug and a Feature Request.

I tried installing custom fonts. It's amazingly simple and great as it solves the local font problem the Aegis system.
The problem starts with the fact that it installed font format is very outdated (TTF) instead of the woff2 format. This has a very bad effect on page loading.

Would there be a way to integrate the woff2 format automatically?

Thanks your work and support Alex!

Best Regards, Patrik

**Comment by alexdeborba** [comment]
Hello @eliquame,

For optimal performance, it is advisable to utilize .woff2 file formats for fonts, as .ttf files can have an impact on site loading times. If you are considering adding a new font, I would recommend checking whether a .woff2 version is available. If not, you can explore online tools that provide the option to convert .ttf files to .woff2, and many of these tools are available for free.

Additionally, if you plan to customize the theme by introducing new fonts, styles, and other modifications, I would strongly recommend implementing these changes within our [child theme](https://github.com/atmostfear-entertainment/aegis-child/releases/tag/1.0.0).

This approach ensures that your customizations are separate from the parent theme, allowing for easier updates and maintenance in the future.

You are very welcome, your kind words are greatly appreciated by both me and the team.
