### ISSUE TITLE
Styling options

### ISSUE THREAD

**Issue by eliquame** [atmostfear-entertainment/aegis#30]
Yes I know, Aegis try to use only default Gutenberg Blocks. But Guti developers slow like sloth.
So, I would like to ask, please add more and more styling option, because not usable it for a really custom and creative design.

Example cant select any position (absolute, relative, ect) to group (container) or stack or other, like cant set up overflow hidden and others.

So I think in 2023 absolute minimum and its absence is unacceptable.

If the gutenberg developers have been unable to do this for at least the last 3 years, it would be great if the Aegis developers would take this step.

Cwicly, Greenshift, Bricks Builder, Breakdance, and others all know the basic style settings.

It would also be great for me if each block has a custom CSS text area and dynamically add an id or class, so that it could be referenced when writing the CSS.

Thanks!
Patrik

**Comment by alexdeborba** [comment]
Hello @eliquame,

Aegis' primary core principle is to maintain as close a connection to the WordPress core as possible, especially concerning blocks. Nonetheless, we are actively exploring methods to further enhance the default blocks without resorting to the creation of a separate blocks plugin, as this is not our preferred approach.

As we continue to depend on the capabilities provided by core blocks and monitor the developments in the Gutenberg plugin, we acknowledge the importance of incorporating the features you mentioned, among others, to enhance the blocks. However, we are actively exploring the most effective approach to implement these enhancements within the theme to ensure flexibility and usability. In this process, we are also considering the use of specific CSS for existing blocks to optimize performance by loading only what is necessary.

I believe it is primarily a matter of patience. As we embark on our gradual journey of innovation, we recognize that many of the features and functionalities that users like yourself require are also essential for our own multisite.

Rest assured, we are committed to making these improvements, and they will come to fruition, sooner or later.
