### ISSUE TITLE
The operation of the blocks is not clean and clear - Group | Stack | Row

### ISSUE THREAD

**Issue by eliquame** [atmostfear-entertainment/aegis#5]
The operation of the blocks is not clean and clear

When I insert a group block (based on what I saw in the Aegis patterns), it offers 3 options in the form of icons as the next step. In fact, depending on the choice, it does not create a group, but a Row or a Stack.

I never understood and liked this kind of logic in Gutenberg, because it completely goes against the usual standards.
I think there would be a much greater need for blocks with clear names and functions, such as "Section", "Container", "Block", "Div".

![image](https://github.com/atmostfear-entertainment/aegis/assets/44946426/b8208191-608c-43a7-9330-43ae057538a8)
![image](https://github.com/atmostfear-entertainment/aegis/assets/44946426/cacf1d93-bde9-4019-8257-7bf6e25a20ce)

**Comment by atmostfear-entertainment** [comment]
Hello @eliquame,

Thank you for sharing your feedback on the Blocks behavior.

We understand where your confusion might be stemming from. The way the Blocks currently work is the default behavior when using them with WordPress. Our theme does not introduce its own unique blocks; instead, it uses the blocks provided by the WordPress Core. This might be the primary source of the confusion you are experiencing.

We do agree with your perspective on how blocks should ideally be named and function. Clear names such as "Section", "Container", "Block", and "Div" would indeed make the user experience more intuitive. However, the current operation and naming conventions of the blocks are reliant on WordPress itself and not our theme.

We will definitely keep your feedback in mind for any future considerations, and we hope that there will be more clarity and improvements in block behavior from WordPress in the near future.

Thank you for using our theme and for your valuable input!
