### ISSUE TITLE
About 1 Block Pattern: Boxed with uneven padding

### ISSUE THREAD

**Issue by atmostfear-entertainment** [atmostfear-entertainment/aegis#9]
**Describe the bug**

Block Pattern appears boxed with uneven padding when added to a page, causing misalignment with other patterns.

When adding a the [About 1 Block Pattern](https://github.com/atmostfear-entertainment/aegis/blob/main/patterns/general/about-1.php) to a page, it is displayed within a boxed container. This container causes the pattern to look out of place, especially when other patterns are added adjacently, aiming for a seamless design. The boxed layout disrupts the continuity of the content. Additionally, there is more padding at the top of the pattern than at the bottom, exacerbating the misalignment.

**To Reproduce**

1. Navigate to the 'Add Pattern' section within the page editor.
2. Select and add the problematic block pattern to the page.
3. Observe the boxed layout around the pattern.
4. Add any other block pattern next to the problematic one.
5. Notice the misalignment and discontinuity in the design.

**Expected behavior**

The block pattern should seamlessly integrate with the page without any boxed layout and should have even padding on all sides, allowing for smooth design continuity when combined with other patterns.

**Actual behavior**

The block pattern is displayed with a boxed layout and has more padding on the top than the bottom. This causes it to look misplaced and disrupts the design continuity when combined with other patterns.

**Screenshots**

![Screenshot](https://github.com/atmostfear-entertainment/aegis/assets/34287288/6aec637d-a911-430f-8b47-de1bd5f1394d)

**Severity**

Minor (This is a visual issue that disrupts design continuity, but does not impede the core functionality of the platform.)

**Additional context**

It would be ideal if this pattern, like others, could be added without any surrounding box or uneven padding, ensuring design uniformity and ease of content creation.

**Comment by alexdeborba** [comment]
![Screenshot](https://github.com/atmostfear-entertainment/aegis/assets/5738223/2546dfab-9d9a-467b-9bde-406fece341d0)

### Changelog:
- Updated group alignment from "wide" to "full".
- Added margin-top and margin-bottom styles to group and columns for consistency.
- Modified the layout type of the group from "constrained" to "default".
- Changed the image source filename from `placeholder_1700x1350_darkcolor.webp` to `thumb_1700x1350_dark.webp`.
- Removed the "what-we-do" class from the columns block.
- General code formatting and cleanup.
